# Generated by Django 5.2.18 on 2026-10-08 10:38

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PipelineStage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                ("position", models.PositiveIntegerField(default=0)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not started"),
                            ("in_progress", "In progress"),
                            ("blocked", "Blocked"),
                            ("done", "Done"),
                        ],
                        default="not_started",
                        max_length=20,
                    ),
                ),
                ("started_on", models.DateField(blank=True, null=True)),
                ("completed_on", models.DateField(blank=True, null=True)),
                ("blocked_reason", models.CharField(blank=True, max_length=300)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["position", "id"],
            },
        ),
        migrations.CreateModel(
            name="Decision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("date", models.DateField(blank=True, null=True)),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                ("title", models.CharField(max_length=250)),
                ("decision", models.TextField(blank=True)),
                ("rationale", models.TextField(blank=True)),
                (
                    "prespecified",
                    models.BooleanField(
                        default=False, help_text="Made before seeing outcome data."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("proposed", "Proposed"),
                            ("adopted", "Adopted"),
                            ("superseded", "Superseded"),
                        ],
                        default="proposed",
                        max_length=12,
                    ),
                ),
                (
                    "superseded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supersedes",
                        to="project.decision",
                    ),
                ),
                (
                    "related_stage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="decisions",
                        to="project.pipelinestage",
                    ),
                ),
            ],
            options={
                "ordering": ["date", "id"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalPipelineStage",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=220)),
                ("position", models.PositiveIntegerField(default=0)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not started"),
                            ("in_progress", "In progress"),
                            ("blocked", "Blocked"),
                            ("done", "Done"),
                        ],
                        default="not_started",
                        max_length=20,
                    ),
                ),
                ("started_on", models.DateField(blank=True, null=True)),
                ("completed_on", models.DateField(blank=True, null=True)),
                ("blocked_reason", models.CharField(blank=True, max_length=300)),
                ("notes", models.TextField(blank=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical pipeline stage",
                "verbose_name_plural": "historical pipeline stages",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalResultEntry",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("title", models.CharField(max_length=200)),
                ("date", models.DateField(default=django.utils.timezone.localdate)),
                (
                    "model_label",
                    models.CharField(
                        choices=[
                            ("M1", "M1 (age + sex)"),
                            ("M2", "M2 (M1 + NfL)"),
                            ("M3", "M3 (M2 + inflammatory proteins)"),
                            ("other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "metric",
                    models.CharField(
                        choices=[
                            ("time_dependent_auc", "Time-dependent AUC"),
                            ("delta_auc", "Delta AUC"),
                            ("c_index", "C-index"),
                            ("calibration_slope", "Calibration slope"),
                            ("brier", "Brier score"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("value", models.DecimalField(decimal_places=4, max_digits=10)),
                (
                    "ci_lower",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "ci_upper",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "horizon_years",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                ("n_participants", models.PositiveIntegerField(blank=True, null=True)),
                ("n_events", models.PositiveIntegerField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "confirmed_permitted",
                    models.BooleanField(
                        default=False,
                        help_text="Ticked to confirm a figure with a low event count is permitted to be shown.",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "linked_stage",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="project.pipelinestage",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical result entry",
                "verbose_name_plural": "historical result entries",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalDecision",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("date", models.DateField(blank=True, null=True)),
                ("slug", models.SlugField(blank=True, max_length=220)),
                ("title", models.CharField(max_length=250)),
                ("decision", models.TextField(blank=True)),
                ("rationale", models.TextField(blank=True)),
                (
                    "prespecified",
                    models.BooleanField(
                        default=False, help_text="Made before seeing outcome data."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("proposed", "Proposed"),
                            ("adopted", "Adopted"),
                            ("superseded", "Superseded"),
                        ],
                        default="proposed",
                        max_length=12,
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "superseded_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="project.decision",
                    ),
                ),
                (
                    "related_stage",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="project.pipelinestage",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical decision",
                "verbose_name_plural": "historical decisions",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="ResultEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("title", models.CharField(max_length=200)),
                ("date", models.DateField(default=django.utils.timezone.localdate)),
                (
                    "model_label",
                    models.CharField(
                        choices=[
                            ("M1", "M1 (age + sex)"),
                            ("M2", "M2 (M1 + NfL)"),
                            ("M3", "M3 (M2 + inflammatory proteins)"),
                            ("other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "metric",
                    models.CharField(
                        choices=[
                            ("time_dependent_auc", "Time-dependent AUC"),
                            ("delta_auc", "Delta AUC"),
                            ("c_index", "C-index"),
                            ("calibration_slope", "Calibration slope"),
                            ("brier", "Brier score"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("value", models.DecimalField(decimal_places=4, max_digits=10)),
                (
                    "ci_lower",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "ci_upper",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "horizon_years",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                ("n_participants", models.PositiveIntegerField(blank=True, null=True)),
                ("n_events", models.PositiveIntegerField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "confirmed_permitted",
                    models.BooleanField(
                        default=False,
                        help_text="Ticked to confirm a figure with a low event count is permitted to be shown.",
                    ),
                ),
                (
                    "linked_stage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="results",
                        to="project.pipelinestage",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "result entries",
                "ordering": ["-date", "-id"],
            },
        ),
    ]
