# Generated by Django 5.2.18 on 2026-10-08 10:38

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_title",
                    models.CharField(
                        default="FTD Inflammation Notebook", max_length=120
                    ),
                ),
                (
                    "tagline",
                    models.CharField(
                        default="Can a minimal inflammatory panel predict incident FTD?",
                        max_length=200,
                    ),
                ),
                ("research_question", models.TextField(blank=True)),
                ("logo", models.ImageField(blank=True, upload_to="logo/")),
                ("primary_colour", models.CharField(default="#1f7a8c", max_length=7)),
                ("footer_text", models.CharField(blank=True, max_length=300)),
                ("public_read", models.BooleanField(default=False)),
                ("min_event_count_warning", models.PositiveIntegerField(default=10)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "site settings",
            },
        ),
        migrations.CreateModel(
            name="HistoricalSiteSettings",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "site_title",
                    models.CharField(
                        default="FTD Inflammation Notebook", max_length=120
                    ),
                ),
                (
                    "tagline",
                    models.CharField(
                        default="Can a minimal inflammatory panel predict incident FTD?",
                        max_length=200,
                    ),
                ),
                ("research_question", models.TextField(blank=True)),
                ("logo", models.TextField(blank=True, max_length=100)),
                ("primary_colour", models.CharField(default="#1f7a8c", max_length=7)),
                ("footer_text", models.CharField(blank=True, max_length=300)),
                ("public_read", models.BooleanField(default=False)),
                ("min_event_count_warning", models.PositiveIntegerField(default=10)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical site settings",
                "verbose_name_plural": "historical site settings",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
