# Generated by Django 5.2.18 on 2026-10-10 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalsitesettings",
            name="weekly_reading_goal",
            field=models.PositiveSmallIntegerField(
                default=3,
                help_text="Papers to finish reading each week. 0 turns the goal off.",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="weekly_reading_goal",
            field=models.PositiveSmallIntegerField(
                default=3,
                help_text="Papers to finish reading each week. 0 turns the goal off.",
            ),
        ),
    ]
