# Generated by Django 5.2.18 on 2026-10-08 10:38

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Protein",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(blank=True, max_length=140, unique=True)),
                ("aliases", models.JSONField(blank=True, default=list)),
                ("olink_assay_name", models.CharField(blank=True, max_length=80)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("cytokine", "Cytokine"),
                            ("chemokine", "Chemokine"),
                            ("cytokine_receptor", "Cytokine receptor"),
                            ("growth_factor", "Growth factor"),
                            ("complement", "Complement"),
                            ("acute_phase", "Acute-phase protein"),
                            ("neurodegeneration_marker", "Neurodegeneration marker"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=30,
                    ),
                ),
                ("on_olink_panel", models.CharField(blank=True, max_length=120)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("candidate", "Candidate"),
                            ("comparator", "Comparator"),
                            ("excluded", "Excluded"),
                            ("selected", "Selected"),
                            ("under_review", "Under review"),
                        ],
                        default="candidate",
                        max_length=20,
                    ),
                ),
                ("rationale", models.TextField(blank=True)),
                ("exclusion_reason", models.CharField(blank=True, max_length=200)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalProtein",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(blank=True, max_length=140)),
                ("aliases", models.JSONField(blank=True, default=list)),
                ("olink_assay_name", models.CharField(blank=True, max_length=80)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("cytokine", "Cytokine"),
                            ("chemokine", "Chemokine"),
                            ("cytokine_receptor", "Cytokine receptor"),
                            ("growth_factor", "Growth factor"),
                            ("complement", "Complement"),
                            ("acute_phase", "Acute-phase protein"),
                            ("neurodegeneration_marker", "Neurodegeneration marker"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=30,
                    ),
                ),
                ("on_olink_panel", models.CharField(blank=True, max_length=120)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("candidate", "Candidate"),
                            ("comparator", "Comparator"),
                            ("excluded", "Excluded"),
                            ("selected", "Selected"),
                            ("under_review", "Under review"),
                        ],
                        default="candidate",
                        max_length=20,
                    ),
                ),
                ("rationale", models.TextField(blank=True)),
                ("exclusion_reason", models.CharField(blank=True, max_length=200)),
                ("notes", models.TextField(blank=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical protein",
                "verbose_name_plural": "historical proteins",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
