# Generated by Django 5.2.18 on 2026-10-08 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proteins", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalprotein",
            name="wikipedia_title",
            field=models.CharField(
                blank=True,
                help_text="Optional. Exact Wikipedia article title; leave blank to find it automatically.",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="protein",
            name="wikipedia_title",
            field=models.CharField(
                blank=True,
                help_text="Optional. Exact Wikipedia article title; leave blank to find it automatically.",
                max_length=200,
            ),
        ),
    ]
