# Generated by Django 5.2.18 on 2026-10-08 10:38

import apps.literature.models
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("proteins", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("name", models.CharField(max_length=60)),
                ("slug", models.SlugField(blank=True, max_length=80, unique=True)),
                ("colour", models.CharField(blank=True, max_length=7)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Finding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("raised", "Raised"),
                            ("lowered", "Lowered"),
                            ("no_difference", "No difference"),
                            ("associated", "Associated"),
                            ("not_associated", "Not associated"),
                            ("predictive", "Predictive"),
                            ("not_predictive", "Not predictive"),
                            ("mixed", "Mixed"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "context",
                    models.CharField(
                        choices=[
                            ("symptomatic_vs_controls", "Symptomatic vs controls"),
                            ("ftd_vs_other_disease", "FTD vs other disease"),
                            (
                                "presymptomatic_vs_noncarriers",
                                "Presymptomatic vs non-carriers",
                            ),
                            ("conversion_prediction", "Conversion prediction"),
                            ("progression_or_survival", "Progression or survival"),
                            (
                                "incident_dementia_population",
                                "Incident dementia (population)",
                            ),
                            ("brain_correspondence", "Brain correspondence"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=40,
                    ),
                ),
                ("context_detail", models.CharField(blank=True, max_length=300)),
                ("effect", models.CharField(blank=True, max_length=300)),
                ("subgroup", models.CharField(blank=True, max_length=300)),
                (
                    "fluid",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("plasma", "Plasma"),
                            ("serum", "Serum"),
                            ("csf", "CSF"),
                            ("brain_tissue", "Brain tissue"),
                            ("pet_imaging", "PET imaging"),
                        ],
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "protein",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="findings",
                        to="proteins.protein",
                    ),
                ),
            ],
            options={
                "ordering": ["paper__citation_number", "protein__name"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalPaper",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "citation_number",
                    models.PositiveIntegerField(blank=True, db_index=True, null=True),
                ),
                ("slug", models.SlugField(blank=True, max_length=200)),
                ("title", models.TextField()),
                ("authors", models.TextField(blank=True)),
                ("first_author_surname", models.CharField(blank=True, max_length=80)),
                ("year", models.PositiveIntegerField(blank=True, null=True)),
                ("journal", models.CharField(blank=True, max_length=200)),
                ("volume", models.CharField(blank=True, max_length=30)),
                ("issue", models.CharField(blank=True, max_length=30)),
                ("pages", models.CharField(blank=True, max_length=40)),
                ("article_number", models.CharField(blank=True, max_length=40)),
                (
                    "doi",
                    models.CharField(
                        blank=True, db_index=True, max_length=200, null=True
                    ),
                ),
                ("url", models.URLField(blank=True)),
                ("ieee_reference", models.TextField(blank=True)),
                (
                    "design",
                    models.CharField(
                        choices=[
                            ("systematic_review", "Systematic review"),
                            ("meta_analysis", "Meta-analysis"),
                            ("cross_sectional", "Cross-sectional"),
                            ("case_control", "Case-control"),
                            ("longitudinal", "Longitudinal"),
                            ("prediction", "Prediction"),
                            ("population_cohort", "Population cohort"),
                            ("progression_model", "Progression model"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=30,
                    ),
                ),
                (
                    "population",
                    models.CharField(
                        choices=[
                            ("sporadic_ftd", "Sporadic FTD"),
                            ("genetic_ftd", "Genetic FTD"),
                            ("mutation_carriers", "Mutation carriers"),
                            ("general_population", "General population"),
                            ("mixed_neurodegenerative", "Mixed neurodegenerative"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=30,
                    ),
                ),
                ("sample_size", models.PositiveIntegerField(blank=True, null=True)),
                ("sample_size_note", models.CharField(blank=True, max_length=200)),
                (
                    "fluids",
                    models.JSONField(
                        blank=True,
                        default=list,
                        validators=[apps.literature.models.validate_fluids],
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("olink", "Olink"),
                            ("somascan", "SomaScan"),
                            ("simoa", "Simoa"),
                            ("luminex", "Luminex"),
                            ("msd", "MSD"),
                            ("elisa", "ELISA"),
                            ("nulisa", "NULISA"),
                            ("other", "Other"),
                            ("mixed", "Mixed"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "review_section",
                    models.CharField(
                        choices=[
                            ("intro", "Introduction"),
                            (
                                "peripheral_inflammation",
                                "Peripheral inflammation in FTD",
                            ),
                            ("presymptomatic", "Before symptom onset"),
                            ("added_value", "Added value beyond blood markers"),
                            ("population_methods", "Population and methods"),
                            ("synthesis", "Synthesis and gap"),
                        ],
                        default="intro",
                        max_length=30,
                    ),
                ),
                ("key_finding", models.TextField(blank=True)),
                ("limitations", models.JSONField(blank=True, default=list)),
                ("notes", models.TextField(blank=True)),
                (
                    "reading_status",
                    models.CharField(
                        choices=[
                            ("to_read", "To read"),
                            ("reading", "Reading"),
                            ("read", "Read"),
                            ("cited", "Cited"),
                        ],
                        default="to_read",
                        max_length=10,
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical paper",
                "verbose_name_plural": "historical papers",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalTag",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("name", models.CharField(max_length=60)),
                ("slug", models.SlugField(blank=True, max_length=80)),
                ("colour", models.CharField(blank=True, max_length=7)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical tag",
                "verbose_name_plural": "historical tags",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Paper",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "citation_number",
                    models.PositiveIntegerField(blank=True, null=True, unique=True),
                ),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                ("title", models.TextField()),
                ("authors", models.TextField(blank=True)),
                ("first_author_surname", models.CharField(blank=True, max_length=80)),
                ("year", models.PositiveIntegerField(blank=True, null=True)),
                ("journal", models.CharField(blank=True, max_length=200)),
                ("volume", models.CharField(blank=True, max_length=30)),
                ("issue", models.CharField(blank=True, max_length=30)),
                ("pages", models.CharField(blank=True, max_length=40)),
                ("article_number", models.CharField(blank=True, max_length=40)),
                (
                    "doi",
                    models.CharField(
                        blank=True, max_length=200, null=True, unique=True
                    ),
                ),
                ("url", models.URLField(blank=True)),
                ("ieee_reference", models.TextField(blank=True)),
                (
                    "design",
                    models.CharField(
                        choices=[
                            ("systematic_review", "Systematic review"),
                            ("meta_analysis", "Meta-analysis"),
                            ("cross_sectional", "Cross-sectional"),
                            ("case_control", "Case-control"),
                            ("longitudinal", "Longitudinal"),
                            ("prediction", "Prediction"),
                            ("population_cohort", "Population cohort"),
                            ("progression_model", "Progression model"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=30,
                    ),
                ),
                (
                    "population",
                    models.CharField(
                        choices=[
                            ("sporadic_ftd", "Sporadic FTD"),
                            ("genetic_ftd", "Genetic FTD"),
                            ("mutation_carriers", "Mutation carriers"),
                            ("general_population", "General population"),
                            ("mixed_neurodegenerative", "Mixed neurodegenerative"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=30,
                    ),
                ),
                ("sample_size", models.PositiveIntegerField(blank=True, null=True)),
                ("sample_size_note", models.CharField(blank=True, max_length=200)),
                (
                    "fluids",
                    models.JSONField(
                        blank=True,
                        default=list,
                        validators=[apps.literature.models.validate_fluids],
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("olink", "Olink"),
                            ("somascan", "SomaScan"),
                            ("simoa", "Simoa"),
                            ("luminex", "Luminex"),
                            ("msd", "MSD"),
                            ("elisa", "ELISA"),
                            ("nulisa", "NULISA"),
                            ("other", "Other"),
                            ("mixed", "Mixed"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "review_section",
                    models.CharField(
                        choices=[
                            ("intro", "Introduction"),
                            (
                                "peripheral_inflammation",
                                "Peripheral inflammation in FTD",
                            ),
                            ("presymptomatic", "Before symptom onset"),
                            ("added_value", "Added value beyond blood markers"),
                            ("population_methods", "Population and methods"),
                            ("synthesis", "Synthesis and gap"),
                        ],
                        default="intro",
                        max_length=30,
                    ),
                ),
                ("key_finding", models.TextField(blank=True)),
                ("limitations", models.JSONField(blank=True, default=list)),
                ("notes", models.TextField(blank=True)),
                (
                    "reading_status",
                    models.CharField(
                        choices=[
                            ("to_read", "To read"),
                            ("reading", "Reading"),
                            ("read", "Read"),
                            ("cited", "Cited"),
                        ],
                        default="to_read",
                        max_length=10,
                    ),
                ),
                (
                    "proteins",
                    models.ManyToManyField(
                        blank=True,
                        related_name="papers",
                        through="literature.Finding",
                        to="proteins.protein",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, related_name="papers", to="literature.tag"
                    ),
                ),
            ],
            options={
                "ordering": ["citation_number", "year", "title"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalFinding",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("raised", "Raised"),
                            ("lowered", "Lowered"),
                            ("no_difference", "No difference"),
                            ("associated", "Associated"),
                            ("not_associated", "Not associated"),
                            ("predictive", "Predictive"),
                            ("not_predictive", "Not predictive"),
                            ("mixed", "Mixed"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "context",
                    models.CharField(
                        choices=[
                            ("symptomatic_vs_controls", "Symptomatic vs controls"),
                            ("ftd_vs_other_disease", "FTD vs other disease"),
                            (
                                "presymptomatic_vs_noncarriers",
                                "Presymptomatic vs non-carriers",
                            ),
                            ("conversion_prediction", "Conversion prediction"),
                            ("progression_or_survival", "Progression or survival"),
                            (
                                "incident_dementia_population",
                                "Incident dementia (population)",
                            ),
                            ("brain_correspondence", "Brain correspondence"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=40,
                    ),
                ),
                ("context_detail", models.CharField(blank=True, max_length=300)),
                ("effect", models.CharField(blank=True, max_length=300)),
                ("subgroup", models.CharField(blank=True, max_length=300)),
                (
                    "fluid",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("plasma", "Plasma"),
                            ("serum", "Serum"),
                            ("csf", "CSF"),
                            ("brain_tissue", "Brain tissue"),
                            ("pet_imaging", "PET imaging"),
                        ],
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "protein",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="proteins.protein",
                    ),
                ),
                (
                    "paper",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="literature.paper",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical finding",
                "verbose_name_plural": "historical findings",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name="finding",
            name="paper",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="findings",
                to="literature.paper",
            ),
        ),
    ]
