# Generated by Django 5.2.18 on 2026-10-08 12:41

import apps.literature.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("literature", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalpaper",
            name="case_identification",
            field=models.CharField(
                blank=True,
                help_text="How cases were identified or diagnosed.",
                max_length=400,
            ),
        ),
        migrations.AddField(
            model_name="historicalpaper",
            name="condition_studied",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ftd", "Frontotemporal dementia"),
                    ("dementia_any", "Dementia (any cause)"),
                    ("alzheimers", "Alzheimer's disease"),
                    ("other_neurodegenerative", "Other neurodegenerative disease"),
                    ("general_population", "General population (no specific disease)"),
                    ("other", "Other"),
                ],
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="historicalpaper",
            name="dataset",
            field=models.CharField(
                blank=True, help_text="Cohort or dataset used.", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="historicalpaper",
            name="extra_details",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Your own tracked details, one per line as "Label: value".',
                validators=[apps.literature.models.validate_string_list],
            ),
        ),
        migrations.AddField(
            model_name="historicalpaper",
            name="ftd_subtypes",
            field=models.JSONField(
                blank=True,
                default=list,
                validators=[apps.literature.models.validate_subtypes],
            ),
        ),
        migrations.AddField(
            model_name="historicalpaper",
            name="methods_to_borrow",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="historicalpaper",
            name="nfl_involved",
            field=models.CharField(
                blank=True,
                choices=[
                    ("not_measured", "Not measured"),
                    ("measured", "Measured, not compared"),
                    ("compared", "Measured and compared (added value tested)"),
                    ("unclear", "Unclear"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="historicalpaper",
            name="quality",
            field=models.CharField(
                blank=True,
                choices=[("high", "High"), ("medium", "Medium"), ("low", "Low")],
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="historicalpaper",
            name="relevance",
            field=models.CharField(
                blank=True,
                choices=[
                    ("core", "Core to my question"),
                    ("useful", "Useful"),
                    ("background", "Background only"),
                ],
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="historicalpaper",
            name="time_frame",
            field=models.CharField(
                blank=True,
                help_text="Follow-up length, or time from blood sample to diagnosis.",
                max_length=300,
            ),
        ),
        migrations.AddField(
            model_name="historicalpaper",
            name="why_it_matters",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="paper",
            name="case_identification",
            field=models.CharField(
                blank=True,
                help_text="How cases were identified or diagnosed.",
                max_length=400,
            ),
        ),
        migrations.AddField(
            model_name="paper",
            name="condition_studied",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ftd", "Frontotemporal dementia"),
                    ("dementia_any", "Dementia (any cause)"),
                    ("alzheimers", "Alzheimer's disease"),
                    ("other_neurodegenerative", "Other neurodegenerative disease"),
                    ("general_population", "General population (no specific disease)"),
                    ("other", "Other"),
                ],
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="paper",
            name="dataset",
            field=models.CharField(
                blank=True, help_text="Cohort or dataset used.", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="paper",
            name="extra_details",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Your own tracked details, one per line as "Label: value".',
                validators=[apps.literature.models.validate_string_list],
            ),
        ),
        migrations.AddField(
            model_name="paper",
            name="ftd_subtypes",
            field=models.JSONField(
                blank=True,
                default=list,
                validators=[apps.literature.models.validate_subtypes],
            ),
        ),
        migrations.AddField(
            model_name="paper",
            name="methods_to_borrow",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="paper",
            name="nfl_involved",
            field=models.CharField(
                blank=True,
                choices=[
                    ("not_measured", "Not measured"),
                    ("measured", "Measured, not compared"),
                    ("compared", "Measured and compared (added value tested)"),
                    ("unclear", "Unclear"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="paper",
            name="quality",
            field=models.CharField(
                blank=True,
                choices=[("high", "High"), ("medium", "Medium"), ("low", "Low")],
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="paper",
            name="relevance",
            field=models.CharField(
                blank=True,
                choices=[
                    ("core", "Core to my question"),
                    ("useful", "Useful"),
                    ("background", "Background only"),
                ],
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="paper",
            name="time_frame",
            field=models.CharField(
                blank=True,
                help_text="Follow-up length, or time from blood sample to diagnosis.",
                max_length=300,
            ),
        ),
        migrations.AddField(
            model_name="paper",
            name="why_it_matters",
            field=models.TextField(blank=True),
        ),
    ]
